# BOARD CONFIG
NUM_OF_THE_SAME_CARDS = 2
SIZE_OF_BOARD = 4
NUM_OF_CARDS = SIZE_OF_BOARD * SIZE_OF_BOARD

# CLIENT COMMANDS
C_SHOW = 'SHOW'  # SHOW X Y

# SERVER COMMANDS
S_START = 'START'  # <-- start game
S_END = 'END'  # END POINTS
S_CARDS = 'CARDS'  # CARDS NAME_1 NAME_2 NAME_3 ...
S_ERROR = 'ERROR'  # <-- invalid command
S_OK = 'OK'

# POINTS
POINTS = 10
