# Generated by Django 4.0 on 2022-03-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_gameroom_points_alter_gameroom_player_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-ended_at']},
        ),
        migrations.AlterModelOptions(
            name='standings',
            options={'ordering': ['-points'], 'verbose_name_plural': 'Standings'},
        ),
        migrations.AlterField(
            model_name='game',
            name='points',
            field=models.IntegerField(default=-1),
        ),
    ]
